### PR TITLE
🧟 Fix Zombie Process

### LINKED ISSUE #316: 🧟 Zombie Process! Process is not terminating
We should be able to initiate a shutdown with: `pkill -15 enclave`

This returns the terminal but doesn't shutdown.

At the end of our integration tests we have some errors when the binaries fail to clean up an open websocket. This prevents them from shutting down gracefully and should be investigated. 

Image

We may want to refactor handles so we get a handle to every async process including and especially the evm_reader and join them.

This should incorporate #162 

---

### To Test

To test alter https://github.com/gnosisguild/enclave/blob/main/tests/integration/base.sh by adding an infinite sleep after launching the nodes:

Image

Then run:

```
pnpm test:integration base
```

Wait for the sleep.

In a second terminal:

```
ps aux | grep enclave
```

You should see the running enclave processes:

Image

Now run in that terminal:

```
pkill -15 -f enclave
```

You will get lots of output detailing a shutdown process:

Image

However there are still running enclave processes:

Image

We can only shut these processes down by running:

```
pkill -9 -f enclave
```

### PR DESCRIPTION
**Pull request by ryardley**
Closes #316 

## Testing

Easiest way to test this is to run the integration tests locally and ensure we don't get errors at the end of the script:

```
pnpm test:integration base
```

This is what the test is doing on `main`:

Image

You can also look at following the test instructions in the #316 issue too. If you want a more focused test.

---

## Summary by CodeRabbit

- **Bug Fixes**
  - Enhanced asynchronous shutdown handling to ensure proper error propagation and prevent indefinite waiting.
  - Improved event stream cleanup by adding robust unsubscription logic with clear success or error feedback.

- **Tests**
  - Refined integration test scripts by adjusting wait durations and process termination commands for more reliable and efficient testing.
  - Added new functions to better manage process counts and graceful shutdowns in integration tests.

- **Chores**
  - Removed unused code to streamline operations and simplify maintenance.
  - Introduced a new shutdown command for improved process termination.

### CODE REVIEW

**Comment by ryardley** [comment]
**Question**: Do we need a test specifically for this to catch regression?

**Comment by ryardley** [comment]
Ok so now if the binary has not completed a graceful shutdown after 10 seconds the test should fail.

File: tests/integration/fns.sh [hunk 1]
```diff
@@ -163,7 +163,22 @@ launch_evm() {
   fi
 }
 
-metallica
+ensure_process_count_equals() {
+  local process_name="$1"
+  local expected_count="$2"
+  local actual_count=$(ps aux | grep "$process_name" | grep -v "grep" | grep -v $$ | wc -l)
+  [ "$actual_count" -eq "$expected_count" ]
+  return $?
```
Comment (hmzakhalid) [inline tests/integration/fns.sh:171]: This can still produce false positives. we should use `pgrep`, which was designed for this exact purpose. For instance:
> 
> ```bash
> local actual_count="$(pgrep -f "$process_name" | wc -l)"
> [ "$actual_count" -eq "$expected_count" ]
> return $?
> ```
> 
This avoids having to manually strip out `grep` processes and is less prone to accidental matches.

**Comment by hmzakhalid** [comment]
tACK - kill em all

File: tests/integration/fns.sh (hunk 1 above)
Comment (ryardley) [reply tests/integration/fns.sh:171]: Can also get false positives with pgrep as I actually was - which is switched to this as it is easier to debug!

File: packages/ciphernode/enclave/src/aggregator_start.rs [hunk 2]
```diff
@@ -17,9 +17,6 @@ pub async fn execute(
         aggregator_start::execute(config, pubkey_write_path, plaintext_write_path).await?;
 
     info!("LAUNCHING AGGREGATOR {}", peer_id);
-    tokio::spawn(listen_for_shutdown(bus.into(), handle));
-
-    std::future::pending::<()>().await;
-
+    tokio::spawn(listen_for_shutdown(bus.into(), handle)).await?;
```
Comment (0xjei) [inline packages/ciphernode/enclave/src/aggregator_start.rs:20]: +1 very neat

File: tests/integration/fns.sh [hunk 3]
```diff
@@ -163,7 +163,22 @@ launch_evm() {
...
+}
+
+gracefull_shutdown() {
+  pkill -15 -f "target/debug/enclave" || true
+  sleep 10
+  ensure_process_count_equals "target/debug/enclave" 0 || return 1
+  kill_em_all
+}
+
+kill_em_all
```
Comment (0xjei) [inline tests/integration/fns.sh:181]: is this duplicated since it's called on `gracefull_shutdown()` or?

**Review by 0xjei — COMMENTED** [review]
uTACK - left some comments

File: tests/integration/fns.sh (hunk 1 above)
Comment (hmzakhalid) [reply tests/integration/fns.sh]: Alrighty!

File: tests/integration/fns.sh (hunk 3 above)
Comment (ryardley) [reply tests/integration/fns.sh:181]: No this runs before every test. Will add a comment.

Comment (0xjei) [reply tests/integration/fns.sh:182]: makes sense, thx for the quick explanation!

**Review by 0xjei — APPROVED** [review]
